[project]
name = 'Distributed-Market-Integration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.existential-risk-hedging]
path = 'contracts/existential-risk-hedging.clar'
clarity_version = 2
epoch = 2.5

[contracts.inter-universal-value-exchange]
path = 'contracts/inter-universal-value-exchange.clar'
clarity_version = 2
epoch = 2.5

[contracts.multiversal-scarcity-management]
path = 'contracts/multiversal-scarcity-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-divergence-futures]
path = 'contracts/reality-divergence-futures.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
